### ISSUE TITLE
Crono runs the task just the first time

### ISSUE THREAD

**Issue by vandamon** [plashchynski/crono#45]
This is an awesome gem, if only it can do what it says.

Crono runs my tasks, but just once, for the first time.

My cronotab looks like this:

```
require 'rake'
Quadra::Application.load_tasks

class InvoiceUpsert
  def perform
    Rake::Task['invoice:batch_upsert'].invoke
  end
end

class PaymentUpsert
  def perform
    Rake::Task['payment:batch_upsert'].invoke
  end
end


Crono.perform(PaymentUpsert).every 1.day, at: { hour: 02, min: 15 }
Crono.perform(InvoiceUpsert).every 15.minutes

```

Any suggestions? Or is this a bug?

**Comment by klausmeyer** [comment]
Try using `Rake::Task#execute` instead of `Rake::Task#invoke`.

Background: Invoke only runs the task "if needed".
Since crono doesn't boot a fresh instance of your application per job execution (like regular cronjobs would do) the task is considered als already executed after the first run if you use `invoke`.

**Comment by vandamon** [comment]
@klausmeyer Thanks a lot for the suggestion. I have it working now.
